### ISSUE TITLE
[Feat] HttpProcessor 뼈대 잡기

### ISSUE THREAD

**Issue by Eunsiho** [CuteWebserv/webserv#33]
## Desc

요청 메세지를 처리하는 HttpProcessor 클래스를 구축합니다. 

## Detail

크게 1차요청처리부(이름 미정), MethodHandler, Response 클래스로 각자 역할을 할 예정입니다.

## Todo

- [ ] HttpProcessor 클래스 생성
- [ ] Makefile정리
- [ ] 각 파트 나누기

**Comment by Elineely** [comment]
Looks good to me!
